# Type  Path                    Mode  User  Group  Age  Argument
d       %h/.ssh                 0700  -     -      -    -
d       %h/.ssh/config.d        0700  -     -      -    -
d       %h/.ssh/keys            0700  -     -      -    -
d       %h/.ssh/sockets         0700  -     -      -    -
f       %h/.ssh/authorized_keys 0600  -     -      -    -
f       %h/.ssh/known_hosts     0600  -     -      -    -

