#!/bin/bash

#
# Automatically adds Jira key to commit message
#

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(main master develop)
  echo $BRANCHES_TO_SKIP
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_NAME="${BRANCH_NAME##*/}"
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_JIRA_KEY=$(echo $BRANCH_NAME | grep -E -o '^([A-Z]+-[0-9]+)')

# Limit to Jira
# if ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $(cat "$1") == "$BRANCH_NAME"* ]] && ! [ -z "$BRANCH_JIRA_KEY" ]; then 
#   echo "$BRANCH_NAME $(cat "${1}")" > "$1"
# fi

if ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $(cat "$1") == "$BRANCH_NAME"* ]]; then
  echo "$BRANCH_NAME: $(cat "${1}")" > "$1"
fi
