#!/bin/bash

# Setup variables; discover where this script is in the filesystem
TARGETDIR=$(cd "$(dirname "$0")/../.config/"; pwd)
# additional iterations that may be viable:
# SCRIPTDIR="$(dirname "$0")"
# SCRIPT_DIR=$(readlink -f ${0%/*})

# Symlink zsh env to dotfiles directory
# ZShell will not look for the environment file in XDG directories by default
ln -s ~/.zshenv $TARGETDIR/zsh/.zshenv 2> /dev/null

completions=(kubectl podman argocd argo k3s k9s kind minikube)
completion_dir_zsh="$TARGETDIR/zsh/.zsh_completions"

for cmd in "${completions[@]}"; do
    if command -v "$cmd" $> /dev/null; then
        "$cmd" completion zsh > "${completion_dir_zsh}/_${cmd}"
    else
        echo "$cmd not found, skipping shell completion"
    fi
done

if command -v gh &> /dev/null; then
    gh completion -s zsh > "${completion_dir_zsh}/_gh" 
else
    echo "gh not found, skipping shell completion"
fi

# TODO - setup bash so bash_history is in XDG
