#options snd_hda_intel index=2,1,0
blacklist snd_rpl_pci_acp6x
blacklist snd_pci_acp6x
blacklist snd_pci_acp5x
blacklist snd_rn_pci_acp3x
blacklist snd_pci_acp3x
blacklist snd_acp_pci
blacklist snd_pci_ps
blacklist snd_sof_amd_acp70
blacklist snd_sof_amd_acp63
blacklist snd_sof_amd_acp
blacklist snd_sof_amd_vangogh
blacklist snd_sof_amd_rembrandt
blacklist snd_sof_amd_renoir
blacklist snd_sof_pci
blacklist snd_sof_acp
options snd slots=snd_hda_intel,snd_hda_intel,snd_hda_intel,snd_usb_audio,snd_usb_audio
options snd_hda_intel index=1,2,0 model=1002:1640,1002:ab40,1022:15e3
options snd_usb_audio index=-4
